const constant = {
    LOADING_STATE: "LOADING_STATE",
    ERROR_STATE: "ERROR_STATE",
    IDLE_STATE: "IDLE_STATE",
    SET_ITEMS: "SET_ITEMS",
    UPDATE_ITEM: "UPDATE_ITEM",
    SET_USER: "SET_USER",
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    REGISTER_USER: "REGISTER_USER",

    ALLOWED_FILE_TYPE: "image/gif",
    MAX_FILE_SIZE: 10485760,        // 10MB 
}

export default constant